# Default values for order-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: deliverairegistry.azurecr.io/apps/order-app
  pullPolicy: Always
  tag: ""

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
    cert-manager.io/acme-challenge-type: "dns01"
    cert-manager.io/acme-dns01-provider: "clouddns"
  hosts:
    - host: order.deliverai.io
      paths: 
        - /
  tls:
   - secretName: ingress-certs
     hosts:
      - "*.deliverai.io"

resources:
  limits:
    cpu: 1
    memory: 2G
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
