image: node:latest

cache:
    paths:
        - node_modules/
        - .yarn

before_script:
    - apt-get update -qq && apt-get install

stages:
    - test

Test:
    stage: test
    before_script:
        - yarn config set cache-folder .yarn
        - yarn install --frozen-lockfile
    script:
        - yarn test
    only:
        refs:
            - merge_requests
            - tags
